In [1]:
import numpy as np



In [2]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [3]:
nestedList = [[1,2], [3,4],[5,6]]
np.array(nestedList)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# built in methods

np.arange(0,10) # stopping point is up to and not including

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.zeros(3) # returns a vector of 3 zeros

array([0., 0., 0.])

In [10]:
np.zeros((4,4), dtype = int) # shape [numrows,numcolumns]

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones(3) # gives u ones

array([1., 1., 1.])

In [13]:
np.ones((4,4), dtype=int) # shape [numrows, numcolumns]

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
np.linspace(0, 10 ,21) #starting point, stopping point (included), number of numbers in between those points

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [16]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [135]:
np.random.rand(3,4)

array([[0.19296835, 0.08552888, 0.82161859, 0.92376721],
       [0.36940608, 0.71713152, 0.10391021, 0.47699859],
       [0.02964126, 0.84030154, 0.63551756, 0.15264404]])

In [137]:
np.random.randn(3,4)

array([[ 0.48920429,  0.95264325, -0.05201906,  0.99075142],
       [ 1.25892589, -0.61929165, -0.49740874, -1.51916014],
       [-0.61952741,  0.27014129, -0.01911258, -0.9236472 ]])

In [169]:
np.random.randint(0, 10, (2,3))

array([[2, 4, 8],
       [1, 3, 4]])

In [170]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [171]:
arr = np.arange(25)

In [172]:
ranarr = np.random.randint(0,50,10)

In [173]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [184]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [185]:
arr.shape

(25,)

In [188]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [191]:
ranarr

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2])

In [192]:
ranarr.max() # returns max works same way with min()

39

In [193]:
ranarr.argmax() # returns index, works same way with argmin()

7