In [1]:
import numpy as np

In [4]:
arr = np.arange(11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[2]

2

In [7]:
arr[1:5] # grab a range of value starting at index 1 and going to index 5 but not including index 5

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5] # start at the beginning and go to 5

array([0, 1, 2, 3, 4])

In [10]:
arr[5:] # starting at index 5 and going to end of array

array([ 5,  6,  7,  8,  9, 10])

In [11]:
# broadcasting
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100 # broadcasting reassignment

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(11)

In [15]:
# slicing
slice_of_arr = arr[0:5]


In [16]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr[:] = 99 # colon means select all elements

In [19]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
# slice of array is pointing to original array therefore will be change in values

In [22]:
arr_copy = arr.copy()

In [24]:
arr_copy[:] = 100

In [25]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [26]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [27]:
# indexing and selection on 2d arrays

In [28]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d.shape # [num rows, num columns]

(3, 3)

In [32]:
arr_2d[0,2] # indexing

15

In [33]:
arr_2d[:2, 1:] # :2 means take rows 0 and 1, 1: means take columns 1 and go to end

array([[10, 15],
       [25, 30]])

In [34]:
# conditional selection

arr = np.arange(11)

In [35]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [36]:
arr2 = arr[arr > 4]

In [37]:
arr2

array([ 5,  6,  7,  8,  9, 10])